name: Upload new release to central

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  run:
    name: Package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SERVER_USER: ${{ secrets.MAVEN_SERVER_USER }}
      SERVER_TOKEN: ${{ secrets.MAVEN_SERVER_PASSWORD }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: SERVER_USER
          server-password: SERVER_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Set up Git user
        run: |
          git config --global user.email "anthony.melin@laposte.net"
          git config --global user.name "Anthony-Melin"
      
      - name: Maven prepare release
        run: mvn release:prepare -DpushChanges=false -Dtag=v1.1.3 -DdevelopmentVersion=1.0.0-SNAPSHOT -DreleaseVersion=1.1.3

      - name: Set up tag
        run: |
          git push --tag origin
          git checkout v1.1.3

      - name: Maven deploy
        run: mvn deploy -DskipTests
